// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use methods::IXCT_ELF;
use risc0_zkvm::{default_prover, ExecutorEnv};

fn main() -> anyhow::Result<()> {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let env = ExecutorEnv::builder().build()?;

    let prover = default_prover();

    let _prove_info = prover.prove(env, IXCT_ELF)?;

    // let _output: u128 = prove_info.receipt.journal.decode()?;
    // println!("output: {}", _output);
    Ok(())
}
